### ISSUE TITLE
why need to strip beginning bytes

### ISSUE THREAD

**Issue by github1youlc** [metachris/flashbotsrpc#13]
I'm confused with the following code. I have tried to figure out why need to strip rlp-encoded beginning bytes, but failed. Wish for your detail !!!

https://github.com/metachris/flashbotsrpc/blob/master/flashbotsrpc.go#L681

		// Might need to strip beginning bytes
		if rlp[:2] == "b9" {
			rlp = rlp[6:]
		} else if rlp[:2] == "b8" {
			rlp = rlp[4:]
		}

**Comment by metachris** [comment]
I don't quite recall anymore, there were some errors otherwise. You could try to remove the code and run a few blocks through it to reproduce.
