### ISSUE TITLE
support for EIP1559?

### ISSUE THREAD

**Issue by xlk3099** [metachris/flashbotsrpc#8]
hi, metachris, glad to see you share this package, 
I am able to wrap up a legacy tx and send mev successfully but when I try to wrap up an EIP1559 tx, the response always shows `unable to decode tx`
I am wondering if this package currently supports EIP1559 txn?

**Comment by metachris** [comment]
Which API are you using - `eth_sendBundle`?

**Comment by YoussifSalama** [comment]
Hey! I think I am having a similar issue.

I get an error when I call `eth_callBundle` by using `rpc.FlashbotsCallBundle` and input an EIP1559 tx (specifically one of type `types.DynamicFeeTx`).

I get the following error when `rpc` is connected to `localhost`:
_relay error response: rlp: expected input list for types.LegacyTx_

And I got the following error when trying to connect to `https://relay.flashbots.net` directly:
_relay error response: unable to decode txs_
